language: ruby

cache: bundler

before_install:
  - gem install bundler

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_head.gemfile

matrix:
  exclude:
    - rvm: 2.2
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_head.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_head.gemfile
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_head.gemfile
  fast_finish: true

notifications:
  email: false
